import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
  <html
    lang="en"
    className={`${geistSans.variable} ${geistMono.variable} h-full antialiased w-full overflow-hidden`}
  >
    {/* conteneur */}
    <body className="w-full h-full flex flex-col overflow-hidden">
      {/* header */}
      <Header />
      {/* l'application centrale + le footer */}
      <div className="flex-1 overflow-y-auto">
        <main className="grid overflow-x-auto min-h-full">
          <div>
            {children}
          </div>
        </main>
        <Footer />
      </div>
    </body>
  </html>
);
}
